sudo: required

language: php

php:
  - 7.0

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - cp .env.travis .env
  - sudo /etc/init.d/postgresql restart
  - psql -c 'select inet_server_port();' -U postgres
  - psql -c 'create database travis_ci_test;' -U postgres
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpcs --standard=psr2 app/
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
